[package]
name = "mixed_cmds"
version = "0.1.0"
authors = ["Light Ning <lightning1141@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irust_api = { path = "../../crates/irust_api/" }
rscript = "0.17.0"
