[package]
name = "printer"
version = "0.4.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2021"
readme = "README.md"
description = "Abstraction over terminal manipulation"
repository = "https://github.com/sigmaSd/IRust/tree/master/crates/printer"
license = "MIT"

[dependencies]
crossterm = "0.22.1"
unicode-width = "0.1.8"
